### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [Arno-co/Osuna_full_stack#1]
- [x] Contains correct datatypes 
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null 
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and back_ticked
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and back_ticked
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and back_ticked

**Comment by linakherchi** [comment]
Good job, Arnaud ! One small addition is that your column names need to be back ticked! 
We will discuss how these tables are setup during our meeting

**Comment by linakherchi** [comment]
Hi Arnaud, 

I was looking at your tables one more time. Do you want to add a row for your tasks checking whether its status is completed or not ?

**Comment by Arno-co** [comment]
Hi Lina,

OK, ça marche!
