### ISSUE TITLE
Wiki Page Home

### ISSUE THREAD

**Issue by linakherchi** [Arno-co/Osuna_full_stack#5]
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

**Comment by linakherchi** [comment]
Thanks Arnaud ! Please add frontend route to your list and put every link as a bullet point.

**Comment by Arno-co** [comment]
I've added the corrections, just need to add the live link when available
